service: ml-kraken-api

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-aws-documentation

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  model-meta-create:
    handler: model-meta/create.create
    events:
      - http:
          path: api/v1/model-meta
          method: post
          cors: true

  model-meta-list:
    handler: model-meta/list.list
    events:
      - http:
          path: api/v1/model-meta
          method: get
          cors: true

  model-meta-get:
    handler: model-meta/get.get
    events:
      - http:
          path: api/v1/model-meta/{id}
          method: get
          cors: true

  model-meta-update:
    handler: model-meta/update.update
    events:
      - http:
          path: api/v1/model-meta/{id}
          method: put
          cors: true

  model-meta-delete:
    handler: model-meta/delete.delete
    events:
      - http:
          path: api/v1/model-meta/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

